### ISSUE TITLE
Fix broken URLs

### ISSUE THREAD

**Issue by anandhu-eng** [mlcommons/mlperf-automations#26]
---

Migrated from https://github.com/mlcommons/mlperf-automations_archived/issues/21
Originally created by @arjunsuresh on *Tue, 17 Sep 2024 14:37:00 GMT*

---
We currently have [many broken links](https://github.com/GATEOverflow/ck/actions/runs/10904300461/job/30260384290) in the README files. Some of these are false positives like the linkedin URLs and private github repo links. It'll be good to replace/remove the broken ones.

**Comment by arjunsuresh** [comment]
Seems to be fine now: https://github.com/mlcommons/mlperf-automations/actions/workflows/check-broken-links.yml
